server:
  port: 8080
  servlet:
    context-path: /redis
spring:
  redis:
    host: 10.5.6.3
    port: 10200
    timeout: 5000ms
    database: 11
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 100ms
        min-idle: 10

